### PR TITLE
Update Coiled logo and Fix broken URLs

### PR DESCRIPTION
**Pull request by avriiil**
This pull requests updates the Coiled logo at the top of the notebook and fixes the broken URLs to Coiled pages.

### CODE REVIEW

**Review by jrbourbeau — APPROVED** [review]
Thanks @rrpelgrim! I just merged the development branch into this PR which should resolve the unrelated CI failures. Planning to merge after CI finishes

**Comment by jrbourbeau** [comment]
Actually, it looks like you might have unintentionally included  a `images/.DS_Store` file. Could you remove that?

**Comment by avriiil** [comment]
@jrbourbeau - I've deleted the .DS_Store and committed. LMK if there's anything else you need to me to change here.

**Comment by jrbourbeau** [comment]
Looks great, thanks @rrpelgrim!

**Pull request merged**
